<?php
require '../config.php';
require '../helpers.php';

/**
 * Run scheduled reports
 * This script should be run via cron (e.g., every hour)
 */

echo "Running scheduled reports...\n";

// Get active schedules that are due
$stmt = $pdo->query("
    SELECT * FROM report_schedules
    WHERE is_active = 1
    AND next_run_at <= NOW()
    ORDER BY next_run_at ASC
");
$schedules = $stmt->fetchAll(PDO::FETCH_ASSOC);

if (empty($schedules)) {
    echo "No schedules due for execution.\n";
    exit;
}

foreach ($schedules as $schedule) {
    echo "Executing schedule: {$schedule['title']}...\n";
    
    // Generate report
    $reportData = generateReportData($schedule['report_type'], json_decode($schedule['filters'], true));
    $filename = generateCSVReport($schedule['report_type'], $reportData);
    
    // Save to database
    $stmt = $pdo->prepare("
        INSERT INTO admin_reports (report_type, title, description, filters, file_path, file_type, generated_by, generated_at, schedule_id)
        VALUES (?, ?, ?, ?, ?, 'csv', NULL, NOW(), ?)
    ");
    $stmt->execute([
        $schedule['report_type'],
        $schedule['title'] . ' - ' . date('Y-m-d H:i:s'),
        'Auto-generated by schedule',
        $schedule['filters'],
        $filename,
        $schedule['id']
    ]);
    
    // Update schedule next run time
    $nextRunAt = calculateNextRunTime($schedule['schedule_type'], $schedule['schedule_day'], $schedule['schedule_time']);
    
    $stmt = $pdo->prepare("
        UPDATE report_schedules
        SET last_run_at = NOW(), next_run_at = ?
        WHERE id = ?
    ");
    $stmt->execute([$nextRunAt, $schedule['id']]);
    
    echo "  - Report generated: {$filename}\n";
    echo "  - Next run: {$nextRunAt}\n";
}

echo "Scheduled reports execution complete.\n";

function generateReportData($reportType, $filters) {
    global $pdo;
    
    $data = [];
    
    switch ($reportType) {
        case 'user_activity':
            $stmt = $pdo->query("
                SELECT 
                    DATE(created_at) as date,
                    COUNT(DISTINCT user_id) as active_users,
                    COUNT(*) as total_events,
                    SUM(time_spent_seconds) as total_time_spent
                FROM learning_analytics
                WHERE created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)
                GROUP BY DATE(created_at)
                ORDER BY date DESC
            ");
            $data = $stmt->fetchAll(PDO::FETCH_ASSOC);
            break;
            
        case 'tryout_results':
            $stmt = $pdo->query("
                SELECT 
                    DATE(created_at) as date,
                    COUNT(*) as total_tryouts,
                    AVG(score) as avg_score,
                    MAX(score) as max_score,
                    MIN(score) as min_score
                FROM tryout_results
                WHERE created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)
                GROUP BY DATE(created_at)
                ORDER BY date DESC
            ");
            $data = $stmt->fetchAll(PDO::FETCH_ASSOC);
            break;
            
        case 'content_performance':
            $stmt = $pdo->query("
                SELECT 
                    subtes,
                    COUNT(DISTINCT soal_id) as total_soal,
                    COUNT(*) as total_views,
                    AVG(CASE WHEN event_type = 'soal_answer' THEN 1 ELSE 0 END) as avg_attempts
                FROM learning_analytics
                WHERE subtes IS NOT NULL AND created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)
                GROUP BY subtes
            ");
            $data = $stmt->fetchAll(PDO::FETCH_ASSOC);
            break;
            
        case 'revenue':
            // Placeholder for revenue tracking
            $data = [
                ['date' => date('Y-m-d'), 'revenue' => 0, 'users' => 0]
            ];
            break;
    }
    
    return $data;
}

function generateCSVReport($reportType, $data) {
    $filename = 'reports/' . $reportType . '_scheduled_' . date('Y-m-d_His') . '.csv';
    $filepath = __DIR__ . '/../' . $filename;
    
    // Create reports directory if not exists
    $dir = dirname($filepath);
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
    }
    
    $file = fopen($filepath, 'w');
    
    if (!empty($data)) {
        // Write header
        fputcsv($file, array_keys($data[0]));
        
        // Write data
        foreach ($data as $row) {
            fputcsv($file, $row);
        }
    }
    
    fclose($file);
    
    return '/' . $filename;
}

function calculateNextRunTime($scheduleType, $scheduleDay, $scheduleTime) {
    $now = new DateTime();
    $time = explode(':', $scheduleTime);
    $hour = (int)$time[0];
    $minute = (int)$time[1];
    
    $nextRun = clone $now;
    $nextRun->setTime($hour, $minute, 0);
    
    switch ($scheduleType) {
        case 'daily':
            $nextRun->modify('+1 day');
            break;
            
        case 'weekly':
            $nextRun->modify('next ' . getDayName($scheduleDay));
            if ($nextRun <= $now) {
                $nextRun->modify('+1 week');
            }
            break;
            
        case 'monthly':
            $nextRun->setDate((int)$nextRun->format('Y'), (int)$nextRun->format('m') + 1, $scheduleDay);
            break;
    }
    
    return $nextRun->format('Y-m-d H:i:s');
}

function getDayName($dayNumber) {
    $days = [1 => 'Monday', 2 => 'Tuesday', 3 => 'Wednesday', 4 => 'Thursday', 5 => 'Friday', 6 => 'Saturday', 7 => 'Sunday'];
    return $days[$dayNumber] ?? 'Monday';
}
