USE skd_cat_bkn;

-- ==================== TKP (30 soal) ====================
INSERT INTO questions (subtes, topik, pertanyaan, pilihan_a, pilihan_b, pilihan_c, pilihan_d, pilihan_e, jawaban_benar, bobot_tkp, pembahasan) VALUES
('TKP', 'Pelayanan Publik', 'Seorang ibu hamil mengantre panjang di loket pelayanan. Ia terlihat lelah. Tindakan Anda...','Biarkan saja karena antrean harus adil','Minta ibu itu menunggu sambil duduk di bangku','Mengajak ibu itu ke loket khusus atau memberikan nomor antrean prioritas','Menyuruhnya pulang dan datang lagi besok','Menyuruh petugas lain menanganinya','C',5,'Melayani kelompok rentan (ibu hamil, lansia, difabel) dengan prioritas adalah pelayanan publik yang humanis.'),
('TKP', 'Pelayanan Publik', 'Anda menemukan sistem komputer kantor mogok saat banyak warga sedang mengantre. Tindakan Anda...','Menutup loket dan menyuruh warga pulang','Menjelaskan situasi, meminta maaf, dan segera hubungi teknisi','Mengabaikan warga dan fokus memperbaiki sendiri','Menyalahkan bagian IT di depan warga','Mengatakan ini bukan tanggung jawab Anda','B',5,'Transparansi dan respons cepat menghadapi kendala teknis adalah integritas pelayanan.'),
('TKP', 'Pelayanan Publik', 'Warga datang 5 menit sebelum jam istirahat makan siang dengan pengajuan yang rumit. Tindakan Anda...','Menyuruhnya datang setelah istirahat','Menerima dan menyelesaikan dengan cepat','Menolak dengan alasan waktu habis','Mengatakan petugas sudah lapar','Menyuruhnya mengurus sendiri via online','B',5,'Melayani kebutuhan warga meski mendekati jam istirahat menunjukkan dedikasi pelayanan publik.'),
('TKP', 'Jejaring Kerja', 'Tim Anda harus menyelesaikan proyek dalam 3 hari, tapi satu anggota sakit. Tindakan Anda...','Mengeluhkan beban berat ke atasan','Mengalokasikan tugas anggota sakit ke anggota lain dengan kompensasi waktu','Menunda deadline tanpa konfirmasi','Mengabaikan tugas anggota yang sakit','Menuntut anggota sakit bekerja dari rumah','B',5,'Mengalokasikan ulang tugas dengan empati dan tetap menjaga kualitas adalah jejaring kerja yang baik.'),
('TKP', 'Jejaring Kerja', 'Di rapat, rekan Anda menyela presentasi Anda dengan kritik pedas. Tindakan Anda...','Membalas kritik dengan cara yang sama','Mendengarkan kritik, mencatat poin valid, dan melanjutkan presentasi dengan tenang','Menghentikan presentasi dan keluar ruangan','Menyuruhnya bicara setelah rapat','Melaporkannya ke atasan karena tidak sopan','B',5,'Menerima kritik dengan dewasa dan profesional adalah tanda jejaring kerja yang matang.'),
('TKP', 'Jejaring Kerja', 'Anda diminta mempresentasikan hasil kerja tim, padahal yang mengerjakan adalah rekan. Tindakan Anda...','Mempresentasikan seolah-olah hasil kerja sendiri','Mempresentasikan dan secara eksplisit menyebut kontribusi masing-masing anggota tim','Menolak karena bukan kerja sendiri','Mengatakan Anda tidak tahu apa-apa','Menyuruh rekan yang mengerjakan untuk presentasi','B',5,'Mengakui kontribusi tim secara terbuka menunjukkan kerja sama yang jujur.'),
('TKP', 'Sosial Budaya', 'Saat dinas luar kota, rekan dari suku lain mengajak Anda mencoba makanan tradisional mereka. Sikap Anda...','Menolak karena tidak suka makanan asing','Menerima dengan senang hati sebagai bentuk penghargaan budaya','Menerima tapi mengeluh di belakang','Menolak dengan alergi palsu','Meminta mereka membelikan makanan yang Anda suka','B',5,'Menerima dan menghargai budaya lokal adalah kesadaran sosial budaya yang tinggi.'),
('TKP', 'Sosial Budaya', 'Di kantor Anda, ada tradisi sholat berjamaah. Anda non-Muslim. Tindakan Anda...','Menghindari ruangan saat sholat berlangsung','Menghormati dan tidak mengganggu, bisa menunggu di ruang lain dengan sopan','Mengkritik tradisi tersebut','Mengajukan komplain ke HRD','Meminta tradisi dihentikan','B',5,'Menghormati keberagaman keyakinan dan tidak mengganggu ibadah orang lain adalah toleransi.'),
('TKP', 'Sosial Budaya', 'Seorang rekan menggunakan bahasa daerah saat rapat yang seharusnya berbahasa Indonesia. Tindakan Anda...','Mengatakan bahwa rapat harus dalam bahasa Indonesia','Mendengarkan dan meminta penjelasan jika tidak paham','Mengabaikan pembicaraan','Menertawakannya','Merekam dan memviralkannya','B',5,'Menghormati keberagaman bahasa sambil meminta klarifikasi dengan sopan menunjukkan apresiasi budaya.'),
('TKP', 'Teknologi Informasi', 'Email kantor Anda terkena phishing yang meminta password. Tindakan Anda...','Mengklik link dan mengisi password','Mengabaikan email tersebut','Melaporkan ke tim IT dan menghapus email','Meneruskan email ke rekan sebagai peringatan tanpa konfirmasi','Membalas email penipu','C',5,'Melaporkan ke IT dan menghapus adalah literasi digital yang benar dalam menghadapi phishing.'),
('TKP', 'Teknologi Informasi', 'Aplikasi internal kantor mengalami update besar yang mengubah seluruh tampilan. Tindakan Anda...','Menolak menggunakan aplikasi baru','Mencoba eksplorasi sendiri, jika stuck meminta bantuan IT','Mengeluh dan mengatakan aplikasi lama lebih baik','Menunggu orang lain mengajari','Membuat akun baru karena lupa cara login','B',5,'Adaptabilitas teknologi dan proaktif meminta bantuan adalah keterampilan digital ASN.'),
('TKP', 'Teknologi Informasi', 'Anda mendapat undangan pertemuan via aplikasi yang belum pernah Anda gunakan. Tindakan Anda...','Tidak menghadiri karena aplikasi asing','Mencoba instal dan ikuti panduan, jika gagal hubungi pengirim','Mengatakan Anda tidak bisa pakai teknologi','Mengirimkan data pribadi ke aplikasi tersebut tanpa verifikasi','Menyuruh rekan mencatat hasil pertemuan untuk Anda','B',5,'Mencoba teknologi baru dengan hati-hati dan verifikasi keaslian adalah literasi digital yang baik.'),
('TKP', 'Profesionalisme', 'Atasan memberikan kritik keras atas laporan Anda di depan rekan kerja. Tindakan Anda...','Membantah dan membela diri di depan umum','Mendengarkan, meminta waktu untuk perbaikan, dan kerjakan dengan lebih baik','Mengabaikan kritik karena merasa sudah benar','Mengeluh di media sosial','Mengancam akan resign','B',5,'Menerima kritik dengan konstruktif dan berusaha memperbaiki adalah profesionalisme tinggi.'),
('TKP', 'Profesionalisme', 'Anda diminta mengganti tugas rekan yang cuti mendadak, padahal Anda sedang sibuk. Tindakan Anda...','Menolak karena tidak sesuai job desk','Menerima, menentukan prioritas, dan komunikasikan ke atasan jika perlu perpanjangan waktu','Menerima tapi mengerjakan asal-asalan','Mengeluh di grup kerja','Mengatakan rekan yang cuti tidak bertanggung jawab','B',5,'Fleksibilitas dan komunikasi terbuka tentang keterbatasan adalah profesionalisme.'),
('TKP', 'Profesionalisme', 'Saat rapat, Anda menyadari data yang Anda bawa salah. Tindakan Anda...','Melanjutkan dengan data palsu','Mengakui kesalahan, meminta maaf, dan janjikan koreksi setelah rapat','Mengatakan data sedang diupdate oleh bagian lain','Mengalihkan pembicaraan','Keluar dari rapat','B',5,'Mengakui kesalahan dan berkomitmen memperbaiki adalah integritas profesionalisme.');
