USE skd_cat_bkn;

-- ==================== TIU (30 soal) ====================
INSERT INTO questions (subtes, tipe, topik, pertanyaan, pilihan_a, pilihan_b, pilihan_c, pilihan_d, pilihan_e, jawaban_benar, pembahasan) VALUES
('TIU', 'verbal', 'Analogi', 'KAPAL : LAUT = ... : ...','Pesawat : Angkasa','Kereta : Rel','Mobil : Ban','Sepeda : Jalan','Bus : Penumpang','A','Hubungan habitat/alat bergerak. Kapal di laut, pesawat di angkasa (udara).'),
('TIU', 'verbal', 'Analogi', 'TUKANG KAYU : PALU = DOKTER : ...','Stetoskop','Pasien','Rumah Sakit','Obat','Bedah','A','Hubungan profesi dengan alat utama. Tukang kayu pakai palu, dokter pakai stetoskop.'),
('TIU', 'verbal', 'Analogi', 'CEPAT : LAMBAT = BANYAK : ...','Sedikit','Banyak','Lebih','Kurang','Tambah','A','Hubungan antonim. Cepat berlawanan dengan lambat, banyak berlawanan dengan sedikit.'),
('TIU', 'verbal', 'Analogi', 'API : PANAS = ES : ...','Dingin','Basah','Cair','Keras','Putih','A','Hubungan sifat. Api bersifat panas, es bersifat dingin.'),
('TIU', 'verbal', 'Analogi', 'KARYAWAN : PERUSAHAAN = MURID : ...','Sekolah','Guru','Kelas','Pelajaran','Ujian','A','Hubungan anggota dengan organisasi. Karyawan di perusahaan, murid di sekolah.'),
('TIU', 'verbal', 'Silogisme', 'Semua pohon adalah tumbuhan. Sebagian tumbuhan berbunga. Maka...','Semua pohon berbunga','Sebagian pohon berbunga','Tidak ada pohon yang berbunga','Semua bunga adalah pohon','Tidak dapat disimpulkan','E','Dari premis "sebagian" + "sebagian" tidak bisa disimpulkan apakah pohon termasuk yang berbunga.'),
('TIU', 'verbal', 'Silogisme', 'Tidak ada kucing yang bisa terbang. Semua burung bisa terbang. Maka...','Semua burung bukan kucing','Ada burung yang kucing','Semua kucing adalah burung','Tidak ada burung yang kucing','Tidak dapat disimpulkan','A','Karena semua burung bisa terbang dan tidak ada kucing yang bisa terbang, maka burung ≠ kucing.'),
('TIU', 'verbal', 'Silogisme', 'Semua mahasiswa IPDN adalah calon PNS. Budi bukan calon PNS. Maka...','Budi mahasiswa IPDN','Budi bukan mahasiswa IPDN','Budi mungkin mahasiswa IPDN','Budi adalah PNS','Tidak dapat disimpulkan','B','Jika semua A adalah B, dan X bukan B, maka X bukan A.'),
('TIU', 'verbal', 'Analitis', 'Rani lebih tua dari Sari. Sari lebih muda dari Mira. Mira lebih muda dari Tini. Siapa paling muda?','Rani','Sari','Mira','Tini','Tidak dapat ditentukan','B','Urutan: Tini > Mira > Rani > Sari. Sari paling muda.'),
('TIU', 'verbal', 'Analitis', 'Dalam satu baris: Andi di sebelah kiri Budi. Candra ada di sebelah kanan Budi. Dedi ada di sebelah kiri Andi. Siapa yang paling kanan?','Andi','Budi','Candra','Dedi','Tidak dapat ditentukan','C','Urutan dari kiri ke kanan: Dedi - Andi - Budi - Candra. Candra paling kanan.'),
('TIU', 'numerik', 'Berhitung', '75% dari 1.200 adalah...','800','850','900','950','1.000','C','75/100 × 1200 = 0,75 × 1200 = 900.'),
('TIU', 'numerik', 'Berhitung', 'Jika a = 5 dan b = -3, nilai dari 3a² + 2b adalah...','63','69','75','81','87','B','3(25) + 2(-3) = 75 - 6 = 69.'),
('TIU', 'numerik', 'Berhitung', 'Akar kuadrat dari 2.025 adalah...','43','44','45','46','47','C','45 × 45 = 2025.'),
('TIU', 'numerik', 'Berhitung', 'Hasil dari (40% dari 250) + (60% dari 150) adalah...','160','170','180','190','200','D','100 + 90 = 190.'),
('TIU', 'numerik', 'Berhitung', 'Bilangan prima antara 20 dan 30 adalah...','21, 23, 27, 29','21, 23, 25, 29','23, 29','21, 23, 29','23, 27, 29','C','Prima: habis dibagi 1 dan dirinya. 23 dan 29 prima. 21=3×7, 25=5×5, 27=3×9.'),
('TIU', 'numerik', 'Deret Angka', '3, 8, 15, 24, 35, ...','44','46','48','50','52','C','Selisih: +5,+7,+9,+11,+13. 35+13=48. Pola kuadratik (n²+2n).'),
('TIU', 'numerik', 'Deret Angka', '2, 3, 5, 8, 13, 21, ...','30','31','33','34','35','D','Fibonacci: 13+21=34.'),
('TIU', 'numerik', 'Deret Angka', '81, 27, 9, 3, ...','0','1','1/3','1/9','1/27','B','Pola: ÷3. 3÷3=1.'),
('TIU', 'numerik', 'Deret Angka', '5, 11, 23, 47, 95, ...','190','191','192','193','194','B','Pola: ×2+1. 5×2+1=11, 11×2+1=23, dst. 95×2+1=191.'),
('TIU', 'numerik', 'Perbandingan', 'Dalam sebuah kantor, perbandingan pegawai PNS dan honorer adalah 5:3. Jika total pegawai 80 orang, berapa PNS?','45','48','50','52','55','C','5/8 × 80 = 50.'),
('TIU', 'numerik', 'Perbandingan', 'Jika 8 orang tukang dapat menyelesaikan rumah dalam 15 hari, berapa hari untuk 12 orang tukang?','8','9','10','11','12','C','Berbalik: 8×15=12×h → h=10.'),
('TIU', 'numerik', 'Soal Cerita', 'Sebuah toko memberi diskon 15% untuk pembelian di atas Rp200.000. Jika harga barang Rp250.000, berapa yang dibayar?','Rp210.000','Rp212.500','Rp215.000','Rp217.500','Rp220.000','B','Diskon 15% dari 250.000 = 37.500. Bayar = 212.500.'),
('TIU', 'numerik', 'Soal Cerita', 'Mobil berangkat pukul 08.00 dari kota A ke kota B (jarak 240 km). Tiba pukul 11.00. Kecepatan rata-rata?','70 km/jam','75 km/jam','80 km/jam','85 km/jam','90 km/jam','C','Waktu = 3 jam. V = 240/3 = 80 km/jam.'),
('TIU', 'numerik', 'Soal Cerita', 'Pak Andi membeli 5 kg jeruk dengan harga Rp25.000/kg. Ia menjual dengan untung 20%. Berapa harga jual per kg?','Rp28.000','Rp29.000','Rp30.000','Rp31.000','Rp32.000','C','Modal = 25.000. Untung 20% = 5.000. Jual = 30.000/kg.'),
('TIU', 'numerik', 'Soal Cerita', 'Dua tahun lalu usia Ayah 4 kali usia Anak. Jika sekarang usia Ayah 40 tahun, berapa usia Anak sekarang?','10','12','13','14','15','B','2 th lalu Ayah 38. Anak 2 th lalu = 38/4 = 9,5 (tidak bulat). Coba: sekarang Ayah 40, 2 th lalu 38. Anak 2 th lalu = 10. Sekarang = 12.'),
('TIU', 'figural', 'Analogi', 'Lingkaran kecil → Lingkaran besar; Persegi kecil → ...','Persegi besar','Persegi panjang','Segitiga besar','Jajaran genjang','Lingkaran','A','Transformasi: ukuran naik. Bentuk tetap persegi → persegi besar.'),
('TIU', 'figural', 'Ketidaksamaan', '5 gambar: segitiga sama sisi, persegi, lingkaran, persegi panjang, belah ketupat. Berbeda?','Segitiga','Persegi','Lingkaran','Persegi panjang','Belah ketupat','C','Lingkaran tidak punya sudut, yang lain punya sudut.'),
('TIU', 'figural', 'Serial', '△, ◇, □, ○, ...','△','◇','□','○','☆','A','Pola bentuk dengan jumlah sudut: 3, 4, 4, 0 (lingkaran). Siklus kembali ke △ (3 sudut).'),
('TIU', 'figural', 'Ketidaksamaan', 'Gambar A-D memiliki garis simetri, gambar E tidak. Yang berbeda?','A','B','C','D','E','E','Simetri adalah ciri pembeda. Gambar E tidak simetris terhadap sumbu manapun.'),
('TIU', 'figural', 'Serial', 'Gambar: titik 1, titik 2, titik 3, ...','Titik 1','Titik 2','Titik 3','Titik 4','Titik 5','E','Pola: jumlah elemen bertambah 1 setiap langkah. 1→2→3→4→5.');
