-- ============================================
-- MIGRASI MATERI SKD LENGKAP
-- Berdasarkan Permen PANRB No. 20/2021
-- ============================================

USE skd_cat_bkn;

-- Hapus materi lama jika ada (opsional)
-- TRUNCATE TABLE materi;

-- ============================================
-- MATERI TWK (Tes Wawasan Kebangsaan)
-- ============================================
INSERT INTO materi (subtes, tipe, judul, konten, urutan) VALUES
('TWK', NULL, 'Pancasila', '<h3>Pengertian Pancasila</h3><p>Pancasila adalah dasar negara dan ideologi bangsa Indonesia. Terdiri dari lima sila:</p><ol><li><strong>Ketuhanan Yang Maha Esa</strong> — Bangsa Indonesia percaya dan taqwa kepada Tuhan Yang Maha Esa.</li><li><strong>Kemanusiaan yang Adil dan Beradab</strong> — Mengakui persamaan hak dan martabat setiap manusia.</li><li><strong>Persatuan Indonesia</strong> — Menjunjung tinggi persatuan dan kesatuan bangsa.</li><li><strong>Kerakyatan yang Dipimpin oleh Hikmat Kebijaksanaan dalam Permusyawaratan/Perwakilan</strong> — Musyawarah untuk mencapai mufakat.</li><li><strong>Keadilan Sosial bagi Seluruh Rakyat Indonesia</strong> — Keadilan ekonomi dan sosial.</li></ol><h3>Sejarah Pancasila</h3><p>Pancasila dirumuskan oleh Soekarno pada Sidang BPUPKI tanggal 1 Juni 1945. Disebut juga sebagai <em>Hari Lahir Pancasila</em>. Rumusan final ditetapkan dalam Pembukaan UUD 1945.</p><h3>Contoh Soal</h3><p><em>Apa makna sila ke-3 Persatuan Indonesia?</em></p><p><strong>Jawaban:</strong> Menjunjung tinggi persatuan dan kesatuan bangsa serta menolak segala bentuk penjajahan dan pemecah belah.</p>', 1),

('TWK', NULL, 'UUD 1945', '<h3>Sejarah UUD 1945</h3><p>UUD 1945 disusun oleh Panitia Persiapan Kemerdekaan Indonesia (PPKI) dan ditetapkan pada tanggal 18 Agustus 1945.</p><h3>Bentuk dan Kedaulatan Negara</h3><p><strong>Bentuk Negara:</strong> Indonesia adalah Negara Kesatuan Republik Indonesia (NKRI).</p><p><strong>Kedaulatan:</strong> Berada di tangan rakyat dan dilaksanakan menurut UUD. (Pasal 1)</p><h3>Hak dan Kewajiban Warga Negara</h3><ul><li>Setiap warga negara berhak atas pekerjaan dan penghidupan yang layak. (Pasal 27)</li><li>Setiap warga negara berhak mendapatkan pendidikan. (Pasal 31)</li><li>Setiap warga negara wajib ikut serta dalam usaha pertahanan dan keamanan negara. (Pasal 27 ayat 3)</li></ul><h3>Lembaga Negara</h3><ul><li><strong>MPR:</strong> Lembaga tertinggi negara yang terdiri dari DPR dan DPD.</li><li><strong>DPR:</strong> Lembaga legislatif yang memiliki fungsi legislasi, anggaran, dan pengawasan.</li><li><strong>BPK:</strong> Lembaga pemeriksa keuangan negara.</li><li><strong>MK:</strong> Mahkamah Konstitusi yang berwenang menguji UU terhadap UUD.</li></ul>', 2),

('TWK', NULL, 'Sejarah Indonesia', '<h3>Masa Penjajahan</h3><p>Indonesia pernah dijajah oleh:</p><ul><li><strong>Portugis</strong> (1511-1605) — Malaka dan Timor</li><li><strong>Spanyol</strong> (1521-1663) — Maluku</li><li><strong>Belanda</strong> (1602-1942) — VOC dan Pemerintah Hindia Belanda</li><li><strong>Jepang</strong> (1942-1945) — Pendudukan militer Jepang</li></ul><h3>Pergerakan Nasional</h3><ul><li><strong>Budi Utomo</strong> (1908) — Organisasi modern pertama, dipimpin dr. Wahidin Soedirohoesodo.</li><li><strong>Indische Partij</strong> (1912) — Organisasi perjuangan politik pertama, dipimpin E.F.E. Douwes Dekker.</li><li><strong>Sarekat Islam</strong> (1912) — Organisasi massa terbesar pada masanya, dipimpin H.O.S. Tjokroaminoto.</li><li><strong>PNI</strong> (1927) — Partai Nasional Indonesia, dipimpin Ir. Soekarno.</li></ul><h3>Proklamasi Kemerdekaan</h3><p>Proklamasi dibacakan oleh Soekarno-Hatta pada tanggal <strong>17 Agustus 1945</strong> di Jalan Pegangsaan Timur 56, Jakarta.</p>', 3),

('TWK', NULL, 'Bela Negara', '<h3>Pengertian Bela Negara</h3><p>Bela negara adalah sikap dan perilaku warga negara yang dijiwai oleh kecintaannya kepada NKRI yang berdasarkan Pancasila dan UUD 1945.</p><h3>Asas Bela Negara</h3><ul><li><strong>Sukarela:</strong> Dilakukan atas dasar kesadaran dan kemauan sendiri.</li><li><strong>Sivil:</strong> Dilakukan oleh seluruh komponen bangsa, bukan hanya militer.</li><li><strong>Universal:</strong> Berlaku untuk seluruh warga negara tanpa membedakan suku, agama, ras, dan golongan.</li></ul><h3>Cara Bela Negara</h3><ol><li>Mengisi kemerdekaan dengan berkarya dan berprestasi.</li><li>Mempertahankan kedaulatan negara.</li><li>Menjaga persatuan dan kesatuan bangsa.</li><li>Meningkatkan kualitas diri untuk kemajuan bangsa.</li><li>Siap berkorban untuk kepentingan bangsa dan negara.</li></ol>', 4),

('TWK', NULL, 'Nasionalisme', '<h3>Pengertian Nasionalisme</h3><p>Nasionalisme adalah paham atau gerakan untuk mempertahankan keutuhan nasional, kedaulatan, dan identitas bangsa.</p><h3>Ciri Nasionalisme Indonesia</h3><ul><li>Bersifat <strong>integratif</strong> — Mempersatukan berbagai suku dan budaya.</li><li>Bersifat <strong>sukarela</strong> — Muncul dari kesadaran kolektif.</li><li>Bersifat <strong>antikolonial</strong> — Menentang penjajahan.</li></ul><h3>Faktor Pendorong Nasionalisme</h3><ol><li>Pendidikan Barat — Memunculkan golongan terpelajar.</li><li>Cetak dan surat kabar — Memperluas jangkauan informasi.</li><li>Organisasi modern — Seperti Budi Utomo dan Sarekat Islam.</li><li>Pengalaman bersama — Penindasan kolonial mempersatukan rakyat.</li></ol><h3>Tokoh Nasionalisme</h3><ul><li>Soekarno — "Bapak Proklamator"</li><li>Hatta — "Bapak Koperasi Indonesia"</li><li>Ki Hajar Dewantara — "Bapak Pendidikan Indonesia"</li><li>Tan Malaka — "Bapak Republik Indonesia"</li></ul>', 5),

('TWK', NULL, 'Bahasa Indonesia', '<h3>EYD (Ejaan Yang Disempurnakan)</h3><p>Peraturan ejaan bahasa Indonesia yang berlaku saat ini adalah <strong>EYD</strong> yang diperbarui dalam <em>Peraturan Bersama KEMDIKBUD dan Kepala BSN 2024</em>.</p><h3>Peribahasa Umum</h3><ul><li><strong>Bagai aur dengan tebing</strong> — Saling membutuhkan.</li><li><strong>Bagai pinang dibelah dua</strong> — Sangat mirip/cocok.</li><li><strong>Bagai isi dengan kuku</strong> — Sangat dekat/akrab.</li><li><strong>Air beriak tanda tak dalam</strong> — Orang sombong biasanya bodoh.</li></ul><h3>Kosakata Baku</h3><table border="1"><tr><th>Tidak Baku</th><th>Baku</th></tr><tr><td>aksen</td><td>aksen (sah)</td></tr><tr><td>analisa</td><td>analisis</td></tr><tr><td>apo</td><td>apa</td></tr><tr><td>aktifitas</td><td>aktivitas</td></tr></table>', 6);

-- ============================================
-- MATERI TIU (Tes Intelegensia Umum)
-- ============================================
INSERT INTO materi (subtes, tipe, judul, konten, urutan) VALUES
('TIU', 'verbal', 'Analogi Verbal', '<h3>Pengertian Analogi</h3><p>Analogi adalah kesesuaian hubungan antara dua pasang kata. Pola umum: <strong>A : B = C : D</strong></p><h3>Jenis-jenis Hubungan</h3><ul><li><strong>Sinonim:</strong> Miskin : Melin = Kaya : Makmur</li><li><strong>Antonim:</strong> Tinggi : Rendah = Besar : Kecil</li><li><strong>Sebab-Akibat:</strong> Virus : Penyakit = Api : Kebakaran</li><li><strong>Bagian-Keseluruhan:</strong> Daun : Pohon = Jari : Tangan</li><li><strong>Fungsi:</strong> Matahari : Terang = Api : Panas</li></ul><h3>Tips Mengerjakan</h3><ol><li>Cari hubungan antara kata pertama dan kedua.</li><li>Cari hubungan yang sama pada pasangan ketiga dan keempat.</li><li>Jika tidak menemukan, coba baca dari belakang.</li></ol>', 7),

('TIU', 'verbal', 'Silogisme', '<h3>Pengertian Silogisme</h3><p>Silogisme adalah penarikan kesimpulan dari dua premis (pernyataan). Pola: <strong>Premis 1 + Premis 2 = Kesimpulan</strong></p><h3>Jenis-jenis Kesimpulan</h3><ul><li><strong>Valid:</strong> Kesimpulan logis dari premis.</li><li><strong>Invalid:</strong> Kesimpulan tidak mendukung premis.</li></ul><h3>Contoh</h3><p><strong>Premis 1:</strong> Semua mamalia menyusui.</p><p><strong>Premis 2:</strong> Semua kucing adalah mamalia.</p><p><strong>Kesimpulan:</strong> Semua kucing menyusui. <em>(Valid)</em></p><h3>Tips</h3><ol><li>Gunakan diagram Venn untuk visualisasi.</li><li>Perhatikan kata universal (semua, tidak ada) vs partikular (beberapa).</li><li>Jangan asumsi di luar premis.</li></ol>', 8),

('TIU', 'verbal', 'Analitis', '<h3>Pengertian TPA Analitis</h3><p>TPA analitis adalah soal yang menguji kemampuan menganalisis informasi dan menarik kesimpulan logis. Biasanya berupa urutan, jadwal, atau posisi.</p><h3>Teknik Penyelesaian</h3><ol><li><strong>Buat tabel atau diagram</strong> — Visualisasikan informasi.</li><li><strong>Identifikasi fakta pasti</strong> — Fakta yang sudah jelas.</li><li><strong>Eliminasi kemungkinan</strong> — Coret yang tidak mungkin.</li><li><strong>Tarik kesimpulan</strong> — Berdasarkan sisa kemungkinan.</li></ol><h3>Contoh</h3><p>A duduk di sebelah B. C duduk di depan D. E duduk di ujung. Siapa di tengah?</p><p><strong>Jawaban:</strong> Buat urutan: E - ? - ? - ? - ?. Dengan eliminasi, tengah adalah B.</p>', 9),

('TIU', 'numerik', 'Berhitung Cepat', '<h3>Trik Perhitungan Cepat</h3><ul><li><strong>Perkalian 11:</strong> 23 x 11 = 2 (2+3) 3 = 253</li><li><strong>Perkalian 25:</strong> 48 x 25 = 48 x 100 / 4 = 1200</li><li><strong>Perkalian 5:</strong> 64 x 5 = 64 x 10 / 2 = 320</li><li><strong>Kuadrat 50-an:</strong> 53² = (25+3) + 3² = 2809</li></ul><h3>Operasi Dasar</h3><table border="1"><tr><th>Operasi</th><th>Sifat</th></tr><tr><td>Penjumlahan</td><td>Komutatif: a+b=b+a</td></tr><tr><td>Perkalian</td><td>Komutatif: ab=ba</td></tr><tr><td>Pengurangan</td><td>Tidak komutatif</td></tr><tr><td>Pembagian</td><td>Tidak komutatif</td></tr></table><h3>Soal Cerita</h3><p>Langkah: 1) Identifikasi variabel, 2) Buat persamaan, 3) Selesaikan.</p>', 10),

('TIU', 'numerik', 'Deret Angka', '<h3>Jenis-jenis Deret</h3><ul><li><strong>Aritmatika:</strong> Beda tetap. Contoh: 2, 5, 8, 11, ... (beda +3)</li><li><strong>Geometri:</strong> Rasio tetap. Contoh: 3, 6, 12, 24, ... (rasio x2)</li><li><strong>Kuadrat:</strong> Berdasarkan pangkat 2. Contoh: 1, 4, 9, 16, 25, ...</li><li><strong>Fibonacci:</strong> Jumlah dua angka sebelumnya. Contoh: 1, 1, 2, 3, 5, 8, ...</li></ul><h3>Tips</h3><ol><li>Cari selisih antar angka.</li><li>Jika selisih tidak tetap, cari pola perkalian atau pembagian.</li><li>Perhatikan pola ganjil-genap atau posisi angka.</li></ol><h3>Contoh</h3><p>2, 6, 12, 20, 30, ...</p><p><strong>Jawaban:</strong> Selisih: +4, +6, +8, +10, jadi selanjutnya +12 = 42.</p>', 11),

('TIU', 'numerik', 'Perbandingan', '<h3>Rasio dan Proporsi</h3><p><strong>Rasio</strong> adalah perbandingan dua besaran. <strong>Proporsi</strong> adalah kesamaan dua rasio.</p><h3>Jenis-jenis Perbandingan</h3><ul><li><strong>Langsung:</strong> Jika A naik, B naik. Contoh: Jumlah barang x Harga.</li><li><strong>Tidak Langsung:</strong> Jika A naik, B turun. Contoh: Kecepatan x Waktu.</li></ul><h3>Rumus</h3><p><strong>Perbandingan:</strong> a : b = c : d → a x d = b x c</p><p><strong>Skala:</strong> Skala = Jarak pada peta / Jarak sebenarnya</p><h3>Contoh Soal Cerita</h3><p>Perbandingan uang A dan B adalah 3:5. Jika total uang mereka Rp 80.000, berapa uang B?</p><p><strong>Jawaban:</strong> B = 5/(3+5) x 80.000 = Rp 50.000</p>', 12),

('TIU', 'figural', 'Figural Analogi', '<h3>Pengertian Figural Analogi</h3><p>Menguji kemampuan melihat hubungan visual antara gambar. Pola: <strong>Gambar A berhubungan dengan Gambar B, maka Gambar C berhubungan dengan?</strong></p><h3>Jenis Transformasi</h3><ul><li><strong>Pencerminan:</strong> Balik horizontal/vertikal.</li><li><strong>Rotasi:</strong> Putar 90°, 180°, 270°.</li><li><strong>Perbesaran/Pengecilan:</strong> Ukuran berubah.</li><li><strong>Penambahan/Pengurangan:</strong> Elemen ditambah atau dihilangkan.</li></ul><h3>Tips</h3><ol><li>Perhatikan perubahan bentuk, ukuran, posisi, dan jumlah elemen.</li><li>Coba terapkan transformasi pada gambar C.</li></ol>', 13),

('TIU', 'figural', 'Figural Ketidaksamaan', '<h3>Pengertian</h3><p>Mencari gambar yang berbeda dari kelompok gambar lainnya.</p><h3>Kriteria Perbedaan</h3><ul><li>Bentuk dasar berbeda.</li><li>Jumlah elemen berbeda.</li><li>Orientasi/posisi berbeda.</li><li>Warna atau pola berbeda.</li></ul><h3>Tips</h3><ol><li>Bandingkan gambar satu per satu.</li><li>Cari pola yang sama pada sebagian besar gambar.</li><li>Gambar yang tidak mengikuti pola adalah jawaban.</li></ol>', 14),

('TIU', 'figural', 'Figural Serial', '<h3>Pengertian</h3><p>Mencari gambar berikutnya dalam suatu urutan pola visual.</p><h3>Jenis Pola</h3><ul><li><strong>Rotasi:</strong> Gambar berputar secara berurutan.</li><li><strong>Penambahan elemen:</strong> Setiap langkah ditambah elemen baru.</li><li><strong>Pergantian posisi:</strong> Elemen berpindah tempat.</li></ul><h3>Tips</h3><ol><li>Amati perubahan dari gambar 1 ke 2, 2 ke 3, dst.</li><li>Identifikasi pola yang konsisten.</li><li>Prediksi gambar selanjutnya berdasarkan pola.</li></ol>', 15);

-- ============================================
-- MATERI TKP (Tes Karakteristik Pribadi)
-- ============================================
INSERT INTO materi (subtes, tipe, judul, konten, urutan) VALUES
('TKP', NULL, 'Pelayanan Publik', '<h3>Prinsip Pelayanan Prima</h3><p>Pelayanan publik harus mengikuti prinsip:</p><ul><li><strong>Transparan:</strong> Informasi jelas dan terbuka.</li><li><strong>Akuntabel:</strong> Bertanggung jawab atas pelayanan.</li><li><strong>Kondisional:</strong> Sesuai ketentuan yang berlaku.</li><li><strong>Partisipatif:</strong> Melibatkan masyarakat.</li></ul><h3>Sikap terhadap Pengguna Layanan</h3><ol><li>Sapa dengan ramah dan sopan.</li><li>Dengarkan keluhan dengan penuh perhatian.</li><li>Berikan solusi yang jelas dan tepat waktu.</li><li>Ucapkan terima kasih setelah pelayanan.</li></ol><h3>Skoring TKP</h3><p>TKP menggunakan skala 1-5. Jawaban terbaik = 5, terburuk = 1.</p>', 16),

('TKP', NULL, 'Jejaring Kerja', '<h3>Kerja Sama Tim</h3><p>Kerja sama tim adalah kemampuan bekerja sama dengan orang lain untuk mencapai tujuan bersama.</p><h3>Komunikasi Efektif</h3><ul><li><strong>Klarifikasi:</strong> Pastikan pesan dipahami dengan benar.</li><li><strong>Empati:</strong> Pahami sudut pandang orang lain.</li><li><strong>Asertif:</strong> Sampaikan pendapat dengan sopan.</li></ul><h3>Koordinasi</h3><ol><li>Tetapkan tujuan bersama.</li><li>Bagi tugas sesuai kemampuan.</li><li>Buat jadwal dan deadline.</li><li>Evaluasi hasil secara berkala.</li></ol>', 17),

('TKP', NULL, 'Sosial Budaya', '<h3>Toleransi dan Kerukunan</h3><p>Indonesia memiliki keberagaman suku, agama, ras, dan golongan. Sikap yang harus dimiliki:</p><ul><li><strong>Menghargai perbedaan:</strong> Setiap budaya memiliki keunikan.</li><li><strong>Tidak mendiskriminasi:</strong> Perlakukan setiap orang setara.</li><li><strong>Melestarikan budaya:</strong> Jaga warisan budaya daerah.</li></ul><h3>Empati Sosial</h3><p>Kemampuan memahami perasaan dan situasi orang lain. Contoh: membantu korban bencana, peduli dengan kelompok rentan.</p>', 18),

('TKP', NULL, 'Teknologi Informasi', '<h3>Etika Digital</h3><p>Penggunaan teknologi informasi harus mengikuti prinsip:</p><ul><li><strong>Jujur:</strong> Tidak menyebarkan hoaks atau informasi palsu.</li><li><strong>Responsibel:</strong> Bertanggung jawab atas konten yang dibuat.</li><li><strong>Menghargai privasi:</strong> Tidak menyebarkan data pribadi orang lain.</li></ul><h3>Pemanfaatan TI untuk Pelayanan</h3><ol><li>E-Government — Layanan pemerintah daring.</li><li>Media sosial resmi — Informasi cepat dan transparan.</li><li>Aplikasi pelayanan publik — Akses mudah 24 jam.</li></ol>', 19),

('TKP', NULL, 'Profesionalisme', '<h3>Sikap Profesional</h3><p>Profesionalisme adalah sikap dan perilaku yang mencerminkan komitmen tinggi terhadap pekerjaan.</p><h3>Komponen Profesionalisme</h3><ul><li><strong>Integritas:</strong> Jujur dan konsisten.</li><li><strong>Komitmen:</strong> Dedikasi terhadap tugas.</li><li><strong>Tanggung jawab:</strong> Bertanggung jawab atas hasil kerja.</li><li><strong>Inisiatif:</strong> Proaktif mencari solusi.</li></ul><h3>Contoh Perilaku Profesional</h3><ol><li>Tepat waktu dalam bekerja.</li><li>Menyelesaikan tugas sesuai deadline.</li><li>Berkomunikasi jika ada masalah.</li><li>Terus belajar dan mengembangkan diri.</li></ol>', 20);

-- ============================================
-- STATISTIK MATERI
-- ============================================
SELECT subtes, COUNT(*) as jumlah FROM materi GROUP BY subtes;
