-- Migration: Add learning analytics
-- Date: 2026-06-07
-- Description: Add tables for learning analytics tracking

CREATE TABLE IF NOT EXISTS learning_analytics (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    event_type ENUM('page_view', 'materi_access', 'soal_view', 'soal_answer', 'quiz_start', 'quiz_complete', 'tryout_start', 'tryout_complete') NOT NULL,
    page_url VARCHAR(500) NULL,
    materi_id INT NULL,
    soal_id INT NULL,
    subtes VARCHAR(10) NULL,
    topik VARCHAR(100) NULL,
    time_spent_seconds INT NULL COMMENT 'Time spent on this page/item',
    session_id VARCHAR(100) NULL,
    user_agent VARCHAR(500) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_user_id (user_id),
    INDEX idx_event_type (event_type),
    INDEX idx_materi_id (materi_id),
    INDEX idx_soal_id (soal_id),
    INDEX idx_subtes (subtes),
    INDEX idx_created_at (created_at),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Learning analytics events';

CREATE TABLE IF NOT EXISTS learning_insights (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    insight_type ENUM('strength', 'weakness', 'recommendation', 'progress') NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    data JSON NULL COMMENT 'Additional data for the insight',
    is_read TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_user_id (user_id),
    INDEX idx_insight_type (insight_type),
    INDEX idx_is_read (is_read),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Generated learning insights for users';

CREATE TABLE IF NOT EXISTS admin_reports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    report_type ENUM('user_activity', 'tryout_results', 'content_performance', 'revenue') NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    filters JSON NULL COMMENT 'Report filters (date range, subtes, etc)',
    file_path VARCHAR(500) NULL COMMENT 'Path to generated file',
    file_type ENUM('pdf', 'excel', 'csv') NULL,
    generated_by INT NULL COMMENT 'Admin who generated',
    generated_at TIMESTAMP NULL DEFAULT NULL,
    schedule_id INT NULL COMMENT 'If generated by schedule',
    INDEX idx_report_type (report_type),
    INDEX idx_generated_at (generated_at),
    INDEX idx_schedule_id (schedule_id),
    FOREIGN KEY (generated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Generated admin reports';

CREATE TABLE IF NOT EXISTS report_schedules (
    id INT AUTO_INCREMENT PRIMARY KEY,
    report_type ENUM('user_activity', 'tryout_results', 'content_performance', 'revenue') NOT NULL,
    title VARCHAR(255) NOT NULL,
    schedule_type ENUM('daily', 'weekly', 'monthly') NOT NULL,
    schedule_day INT NULL COMMENT 'Day of week (1-7) or day of month (1-31)',
    schedule_time TIME NULL,
    filters JSON NULL COMMENT 'Report filters',
    is_active TINYINT(1) DEFAULT 1,
    last_run_at TIMESTAMP NULL,
    next_run_at TIMESTAMP NULL,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_report_type (report_type),
    INDEX idx_is_active (is_active),
    INDEX idx_next_run_at (next_run_at),
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Scheduled report generation';
