-- MySQL dump 10.13  Distrib 8.0.46, for Linux (x86_64)
--
-- Host: localhost    Database: skd_cat_bkn
-- ------------------------------------------------------
-- Server version	5.5.5-10.4.32-MariaDB

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `admin_reports`
--

DROP TABLE IF EXISTS `admin_reports`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `admin_reports` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `report_type` enum('user_activity','tryout_results','content_performance','revenue') NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `filters` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Report filters (date range, subtes, etc)' CHECK (json_valid(`filters`)),
  `file_path` varchar(500) DEFAULT NULL COMMENT 'Path to generated file',
  `file_type` enum('pdf','excel','csv') DEFAULT NULL,
  `generated_by` int(11) DEFAULT NULL COMMENT 'Admin who generated',
  `generated_at` timestamp NULL DEFAULT NULL,
  `schedule_id` int(11) DEFAULT NULL COMMENT 'If generated by schedule',
  PRIMARY KEY (`id`),
  KEY `idx_report_type` (`report_type`),
  KEY `idx_generated_at` (`generated_at`),
  KEY `idx_schedule_id` (`schedule_id`),
  KEY `generated_by` (`generated_by`),
  CONSTRAINT `admin_reports_ibfk_1` FOREIGN KEY (`generated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Generated admin reports';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `answers`
--

DROP TABLE IF EXISTS `answers`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `answers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session_id` int(11) NOT NULL,
  `question_id` int(11) NOT NULL,
  `jawaban_user` char(1) DEFAULT NULL,
  `skor` int(11) DEFAULT 0,
  `waktu_dijawab` timestamp NOT NULL DEFAULT current_timestamp(),
  `is_ragu` tinyint(4) DEFAULT 0 COMMENT 'Doubt flag: 1 = ragu-ragu, 0 = tidak ragu',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_session_question` (`session_id`,`question_id`),
  KEY `question_id` (`question_id`),
  KEY `idx_answers_session` (`session_id`),
  KEY `idx_answers_question` (`question_id`),
  CONSTRAINT `answers_ibfk_1` FOREIGN KEY (`session_id`) REFERENCES `tryout_sessions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `answers_ibfk_2` FOREIGN KEY (`question_id`) REFERENCES `questions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11158 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `api_performance_log`
--

DROP TABLE IF EXISTS `api_performance_log`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `api_performance_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `endpoint` varchar(255) NOT NULL,
  `method` varchar(10) NOT NULL,
  `response_time_ms` int(11) NOT NULL,
  `status_code` int(11) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `ip_address` varchar(45) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_endpoint` (`endpoint`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_status_code` (`status_code`),
  KEY `idx_created_at_cleanup` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=281 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `api_rate_limit_stats`
--

DROP TABLE IF EXISTS `api_rate_limit_stats`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `api_rate_limit_stats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `endpoint` varchar(255) NOT NULL,
  `identifier` varchar(255) NOT NULL,
  `blocked` tinyint(1) DEFAULT 0,
  `request_count` int(11) DEFAULT 1,
  `window_start` timestamp NOT NULL DEFAULT current_timestamp(),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_endpoint` (`endpoint`),
  KEY `idx_identifier` (`identifier`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_blocked` (`blocked`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `api_rate_limits`
--

DROP TABLE IF EXISTS `api_rate_limits`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `api_rate_limits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `identifier` varchar(255) NOT NULL,
  `endpoint` varchar(100) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_identifier_endpoint` (`identifier`,`endpoint`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_api_rate_limits_created` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=6268 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `audit_logs`
--

DROP TABLE IF EXISTS `audit_logs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `audit_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `action` varchar(100) NOT NULL,
  `entity_type` varchar(50) DEFAULT NULL,
  `entity_id` int(11) DEFAULT NULL,
  `details` text DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_action` (`action`),
  KEY `idx_entity` (`entity_type`,`entity_id`),
  KEY `idx_created_at` (`created_at`),
  CONSTRAINT `audit_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `content_moderation`
--

DROP TABLE IF EXISTS `content_moderation`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `content_moderation` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `content_type` enum('question','materi','comment') NOT NULL,
  `content_id` int(11) NOT NULL,
  `reporter_id` int(11) DEFAULT NULL COMMENT 'User who reported the content (null if auto-flagged)',
  `reason` text DEFAULT NULL COMMENT 'Reason for flagging',
  `status` enum('pending','approved','rejected','deleted') DEFAULT 'pending',
  `moderator_id` int(11) DEFAULT NULL COMMENT 'Admin who reviewed',
  `moderator_note` text DEFAULT NULL COMMENT 'Note from moderator',
  `reviewed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_content` (`content_type`,`content_id`),
  KEY `reporter_id` (`reporter_id`),
  KEY `moderator_id` (`moderator_id`),
  CONSTRAINT `content_moderation_ibfk_1` FOREIGN KEY (`reporter_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `content_moderation_ibfk_2` FOREIGN KEY (`moderator_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Content moderation queue for flagged content';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `daily_quiz_answers`
--

DROP TABLE IF EXISTS `daily_quiz_answers`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `daily_quiz_answers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session_id` int(11) NOT NULL,
  `question_id` int(11) NOT NULL,
  `jawaban_user` char(1) DEFAULT NULL,
  `is_ragu` tinyint(4) DEFAULT 0,
  `waktu_jawab` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_session_question` (`session_id`,`question_id`),
  KEY `question_id` (`question_id`),
  CONSTRAINT `daily_quiz_answers_ibfk_1` FOREIGN KEY (`session_id`) REFERENCES `daily_quiz_sessions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `daily_quiz_answers_ibfk_2` FOREIGN KEY (`question_id`) REFERENCES `questions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=785 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `daily_quiz_questions`
--

DROP TABLE IF EXISTS `daily_quiz_questions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `daily_quiz_questions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session_id` int(11) NOT NULL,
  `question_id` int(11) NOT NULL,
  `subtes` varchar(10) NOT NULL,
  `urutan` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `session_id` (`session_id`),
  KEY `question_id` (`question_id`),
  CONSTRAINT `daily_quiz_questions_ibfk_1` FOREIGN KEY (`session_id`) REFERENCES `daily_quiz_sessions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `daily_quiz_questions_ibfk_2` FOREIGN KEY (`question_id`) REFERENCES `questions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=171 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `daily_quiz_sessions`
--

DROP TABLE IF EXISTS `daily_quiz_sessions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `daily_quiz_sessions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `quiz_date` date NOT NULL,
  `waktu_mulai` datetime DEFAULT current_timestamp(),
  `waktu_selesai` datetime DEFAULT NULL,
  `status` enum('berjalan','selesai') DEFAULT 'berjalan',
  `total_soal` int(11) DEFAULT 10,
  `benar` int(11) DEFAULT 0,
  `salah` int(11) DEFAULT 0,
  `kosong` int(11) DEFAULT 0,
  `nilai_total` int(11) DEFAULT 0,
  `scheduled_subtes` varchar(10) DEFAULT NULL COMMENT 'Scheduled subtes for the day',
  `scheduled_topik` varchar(100) DEFAULT NULL COMMENT 'Scheduled topic for the day',
  `difficulty` enum('mudah','sedang','sulit') DEFAULT 'sedang' COMMENT 'Difficulty level of the quiz',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_daily` (`user_id`,`quiz_date`),
  CONSTRAINT `daily_quiz_sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `daily_quiz_streaks`
--

DROP TABLE IF EXISTS `daily_quiz_streaks`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `daily_quiz_streaks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `current_streak` int(11) DEFAULT 0 COMMENT 'Current consecutive days',
  `longest_streak` int(11) DEFAULT 0 COMMENT 'Longest streak achieved',
  `last_quiz_date` date DEFAULT NULL COMMENT 'Last date user completed daily quiz',
  `total_quizzes` int(11) DEFAULT 0 COMMENT 'Total daily quizzes completed',
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  CONSTRAINT `daily_quiz_streaks_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Daily quiz streak tracking';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `daily_quiz_topic_schedule`
--

DROP TABLE IF EXISTS `daily_quiz_topic_schedule`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `daily_quiz_topic_schedule` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `day_of_week` tinyint(4) NOT NULL COMMENT '0=Sunday, 1=Monday, ..., 6=Saturday',
  `subtes` varchar(10) NOT NULL,
  `topik` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_day` (`day_of_week`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Daily quiz topic schedule by day';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `error_log`
--

DROP TABLE IF EXISTS `error_log`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `error_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `error_type` varchar(50) NOT NULL,
  `error_message` text NOT NULL,
  `file_path` varchar(255) DEFAULT NULL,
  `line_number` int(11) DEFAULT NULL,
  `stack_trace` text DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `ip_address` varchar(45) NOT NULL,
  `user_agent` text DEFAULT NULL,
  `request_uri` text DEFAULT NULL,
  `request_method` varchar(10) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_error_type` (`error_type`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_created_at_cleanup` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `instansi`
--

DROP TABLE IF EXISTS `instansi`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `instansi` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `kode` varchar(20) NOT NULL COMMENT 'Singkatan: STAN, STIS, IPDN, dll',
  `nama` varchar(100) NOT NULL COMMENT 'Nama lengkap instansi',
  `passing_twk` int(11) NOT NULL DEFAULT 65,
  `passing_tiu` int(11) NOT NULL DEFAULT 80,
  `passing_tkp` int(11) NOT NULL DEFAULT 126,
  `passing_total` int(11) NOT NULL DEFAULT 271,
  `deskripsi` text DEFAULT NULL COMMENT 'Info singkat instansi',
  `aktif` tinyint(1) DEFAULT 1,
  `urutan` int(11) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_kode` (`kode`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `leaderboard_badges`
--

DROP TABLE IF EXISTS `leaderboard_badges`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `leaderboard_badges` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `badge_type` varchar(50) NOT NULL,
  `badge_name` varchar(100) NOT NULL,
  `badge_icon` varchar(50) DEFAULT '­ƒÅå',
  `badge_color` varchar(20) DEFAULT '#f1c40f',
  `earned_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `period_start` date DEFAULT NULL COMMENT 'For time-based badges',
  `period_end` date DEFAULT NULL COMMENT 'For time-based badges',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_badge_period` (`user_id`,`badge_type`,`period_start`),
  CONSTRAINT `leaderboard_badges_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Leaderboard badges and achievements';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `learning_analytics`
--

DROP TABLE IF EXISTS `learning_analytics`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `learning_analytics` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `event_type` enum('page_view','materi_access','soal_view','soal_answer','quiz_start','quiz_complete','tryout_start','tryout_complete') NOT NULL,
  `page_url` varchar(500) DEFAULT NULL,
  `materi_id` int(11) DEFAULT NULL,
  `soal_id` int(11) DEFAULT NULL,
  `subtes` varchar(10) DEFAULT NULL,
  `topik` varchar(100) DEFAULT NULL,
  `time_spent_seconds` int(11) DEFAULT NULL COMMENT 'Time spent on this page/item',
  `session_id` varchar(100) DEFAULT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_event_type` (`event_type`),
  KEY `idx_materi_id` (`materi_id`),
  KEY `idx_soal_id` (`soal_id`),
  KEY `idx_subtes` (`subtes`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_learning_analytics_user` (`user_id`),
  KEY `idx_learning_analytics_event` (`event_type`),
  KEY `idx_learning_analytics_created` (`created_at`),
  CONSTRAINT `learning_analytics_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=231 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Learning analytics events';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `learning_insights`
--

DROP TABLE IF EXISTS `learning_insights`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `learning_insights` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `insight_type` enum('strength','weakness','recommendation','progress') NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Additional data for the insight' CHECK (json_valid(`data`)),
  `is_read` tinyint(1) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_insight_type` (`insight_type`),
  KEY `idx_is_read` (`is_read`),
  CONSTRAINT `learning_insights_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Generated learning insights for users';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `master_materi`
--

DROP TABLE IF EXISTS `master_materi`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `master_materi` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `subtes` enum('TKP','TIU','TWK') NOT NULL,
  `tipe` varchar(50) DEFAULT NULL,
  `topik` varchar(100) NOT NULL,
  `kisi_kisi` text NOT NULL COMMENT 'Acuan untuk AI generate soal',
  `level` enum('mudah','sedang','sulit') DEFAULT 'sedang',
  `aktif` tinyint(1) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `materi`
--

DROP TABLE IF EXISTS `materi`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `materi` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `subtes` enum('TKP','TIU','TWK') NOT NULL,
  `tipe` varchar(20) DEFAULT NULL,
  `judul` varchar(200) NOT NULL,
  `konten` text NOT NULL,
  `url` varchar(255) DEFAULT NULL,
  `urutan` int(11) DEFAULT 0,
  `is_active` tinyint(1) DEFAULT 1 COMMENT 'Active status for materi',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `created_by` int(11) DEFAULT NULL COMMENT 'User who created materi',
  `updated_by` int(11) DEFAULT NULL COMMENT 'User who last updated materi',
  PRIMARY KEY (`id`),
  KEY `idx_is_active` (`is_active`),
  KEY `idx_subtes` (`subtes`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `materi_bookmarks`
--

DROP TABLE IF EXISTS `materi_bookmarks`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `materi_bookmarks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `materi_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_materi` (`user_id`,`materi_id`),
  KEY `materi_id` (`materi_id`),
  CONSTRAINT `materi_bookmarks_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `materi_bookmarks_ibfk_2` FOREIGN KEY (`materi_id`) REFERENCES `materi` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='User bookmarks for learning materials';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `materi_progress`
--

DROP TABLE IF EXISTS `materi_progress`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `materi_progress` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `materi_id` int(11) NOT NULL,
  `progress_percent` int(11) DEFAULT 0 COMMENT 'Reading progress percentage (0-100)',
  `last_position` int(11) DEFAULT 0 COMMENT 'Last scroll position in pixels',
  `last_read_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_materi` (`user_id`,`materi_id`),
  KEY `materi_id` (`materi_id`),
  CONSTRAINT `materi_progress_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `materi_progress_ibfk_2` FOREIGN KEY (`materi_id`) REFERENCES `materi` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='User reading progress for materials';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `media_library`
--

DROP TABLE IF EXISTS `media_library`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `media_library` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `filename` varchar(255) NOT NULL,
  `original_name` varchar(255) NOT NULL,
  `file_path` varchar(500) NOT NULL,
  `file_url` varchar(500) NOT NULL,
  `file_type` enum('image','video','document') NOT NULL,
  `file_size` int(11) NOT NULL COMMENT 'Size in bytes',
  `mime_type` varchar(100) NOT NULL,
  `folder` varchar(100) DEFAULT 'general',
  `uploaded_by` int(11) DEFAULT NULL COMMENT 'User who uploaded',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_file_type` (`file_type`),
  KEY `idx_folder` (`folder`),
  KEY `uploaded_by` (`uploaded_by`),
  CONSTRAINT `media_library_ibfk_1` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Media library for admin content management';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `notification_logs`
--

DROP TABLE IF EXISTS `notification_logs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `notification_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `type` enum('daily_quiz','live_class','new_materi','tryout_result','general') NOT NULL,
  `title` varchar(255) NOT NULL,
  `body` text NOT NULL,
  `data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Additional data for the notification' CHECK (json_valid(`data`)),
  `sent_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_type` (`type`),
  KEY `idx_sent_at` (`sent_at`),
  CONSTRAINT `notification_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Notification send logs';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `notification_preferences`
--

DROP TABLE IF EXISTS `notification_preferences`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `notification_preferences` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `daily_quiz_reminder` tinyint(1) DEFAULT 1 COMMENT 'Daily quiz reminder notifications',
  `live_class_starting` tinyint(1) DEFAULT 1 COMMENT 'Live class starting notifications',
  `new_materi_available` tinyint(1) DEFAULT 1 COMMENT 'New materi available notifications',
  `tryout_result_ready` tinyint(1) DEFAULT 1 COMMENT 'Tryout result ready notifications',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user` (`user_id`),
  CONSTRAINT `notification_preferences_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='User notification preferences';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `notifications`
--

DROP TABLE IF EXISTS `notifications`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `notifications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `type` enum('info','success','warning','error') DEFAULT 'info',
  `title` varchar(255) NOT NULL,
  `message` text NOT NULL,
  `link` varchar(500) DEFAULT NULL,
  `is_read` tinyint(1) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_read` (`user_id`,`is_read`),
  KEY `idx_created` (`created_at`),
  KEY `idx_notifications_user_read` (`user_id`,`is_read`),
  CONSTRAINT `notifications_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `passages`
--

DROP TABLE IF EXISTS `passages`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `passages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `subtes` enum('TKP','TIU','TWK') NOT NULL,
  `tipe` varchar(20) DEFAULT NULL,
  `topik` varchar(100) NOT NULL,
  `judul` varchar(200) DEFAULT NULL,
  `bacaan` text NOT NULL,
  `aktif` tinyint(4) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `password_reset_requests`
--

DROP TABLE IF EXISTS `password_reset_requests`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `password_reset_requests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `email` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `status` enum('pending','completed') DEFAULT 'pending',
  `no_hp` varchar(20) DEFAULT NULL COMMENT 'Nomor HP user',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created` (`created_at`),
  CONSTRAINT `password_reset_requests_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `performance_reports`
--

DROP TABLE IF EXISTS `performance_reports`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `performance_reports` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `report_type` enum('weekly','monthly') NOT NULL,
  `report_date` date NOT NULL,
  `period_start` date NOT NULL,
  `period_end` date NOT NULL,
  `total_tryouts` int(11) DEFAULT 0,
  `avg_tryout_score` decimal(5,2) DEFAULT 0.00,
  `total_daily_quizzes` int(11) DEFAULT 0,
  `avg_daily_quiz_score` decimal(5,2) DEFAULT 0.00,
  `current_streak` int(11) DEFAULT 0,
  `total_practice_sessions` int(11) DEFAULT 0,
  `recommendations` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_period` (`user_id`,`report_type`,`report_date`),
  CONSTRAINT `performance_reports_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='User performance reports';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `personal_practice_sessions`
--

DROP TABLE IF EXISTS `personal_practice_sessions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `personal_practice_sessions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `subtes` varchar(10) NOT NULL,
  `topik` varchar(100) DEFAULT NULL,
  `jumlah_soal` int(11) NOT NULL,
  `tingkat_kesulitan` enum('mudah','sedang','sulit') DEFAULT 'sedang',
  `benar` int(11) DEFAULT 0,
  `salah` int(11) DEFAULT 0,
  `skor` int(11) DEFAULT 0,
  `waktu_mulai` timestamp NOT NULL DEFAULT current_timestamp(),
  `waktu_selesai` timestamp NULL DEFAULT NULL,
  `timer_mode` varchar(20) DEFAULT NULL COMMENT 'Timer mode: none, per-question, or total',
  `timer_used_seconds` int(11) DEFAULT NULL COMMENT 'Total time used in seconds',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `personal_practice_sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Personal practice session tracking';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `push_subscriptions`
--

DROP TABLE IF EXISTS `push_subscriptions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `push_subscriptions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `endpoint` varchar(500) NOT NULL,
  `p256dh` varchar(255) NOT NULL,
  `auth` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  CONSTRAINT `push_subscriptions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Push notification subscriptions';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `question_bookmarks`
--

DROP TABLE IF EXISTS `question_bookmarks`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `question_bookmarks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `question_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_question` (`user_id`,`question_id`),
  KEY `question_id` (`question_id`),
  CONSTRAINT `question_bookmarks_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `question_bookmarks_ibfk_2` FOREIGN KEY (`question_id`) REFERENCES `questions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `question_options`
--

DROP TABLE IF EXISTS `question_options`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `question_options` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `question_id` int(11) NOT NULL,
  `opsi_label` char(1) NOT NULL COMMENT 'A/B/C/D/E',
  `opsi_teks` text NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_question_opsi` (`question_id`,`opsi_label`),
  KEY `idx_question_options_question` (`question_id`),
  CONSTRAINT `question_options_ibfk_1` FOREIGN KEY (`question_id`) REFERENCES `questions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6391 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `questions`
--

DROP TABLE IF EXISTS `questions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `questions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `subtes` enum('TKP','TIU','TWK') NOT NULL,
  `tipe` varchar(20) DEFAULT NULL COMMENT 'verbal|numerik|figural untuk TIU',
  `topik` varchar(100) NOT NULL,
  `difficulty` enum('mudah','sedang','sulit') DEFAULT 'sedang',
  `pertanyaan` text NOT NULL,
  `pilihan_a` text NOT NULL,
  `pilihan_b` text NOT NULL,
  `pilihan_c` text NOT NULL,
  `pilihan_d` text NOT NULL,
  `pilihan_e` text NOT NULL,
  `jawaban_benar` varchar(255) DEFAULT NULL,
  `bobot_tkp` int(11) DEFAULT NULL COMMENT '1-5 untuk TKP; NULL untuk TIU/TWK',
  `bobot_a` int(11) DEFAULT NULL,
  `bobot_b` int(11) DEFAULT NULL,
  `bobot_c` int(11) DEFAULT NULL,
  `bobot_d` int(11) DEFAULT NULL,
  `bobot_e` int(11) DEFAULT NULL,
  `pembahasan` text NOT NULL,
  `tips_trick` text DEFAULT NULL,
  `related_links` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`related_links`)),
  `materi_id` int(11) DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `passage_id` int(11) DEFAULT NULL,
  `passage_order` int(11) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `needs_revision` tinyint(1) NOT NULL DEFAULT 0,
  `revision_status` varchar(20) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pertanyaan` (`pertanyaan`) USING HASH,
  KEY `passage_id` (`passage_id`),
  KEY `idx_questions_needs_revision` (`needs_revision`),
  KEY `idx_questions_is_active` (`is_active`),
  KEY `idx_questions_subtes_topik` (`subtes`,`topik`),
  KEY `idx_questions_created` (`created_at`),
  KEY `idx_questions_subtes_active` (`subtes`,`is_active`,`created_at`),
  KEY `idx_questions_revision` (`needs_revision`,`revision_status`),
  CONSTRAINT `questions_ibfk_1` FOREIGN KEY (`passage_id`) REFERENCES `passages` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=2679 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `rate_limits`
--

DROP TABLE IF EXISTS `rate_limits`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `rate_limits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ip` varchar(45) NOT NULL,
  `count` int(11) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ip_created` (`ip`,`created_at`),
  KEY `idx_rate_limits_ip` (`ip`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `rekomendasi_materi`
--

DROP TABLE IF EXISTS `rekomendasi_materi`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `rekomendasi_materi` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `subtes` enum('TKP','TIU','TWK') NOT NULL,
  `topik` varchar(100) NOT NULL,
  `materi_url` varchar(200) NOT NULL COMMENT 'Link ke materi.php',
  `pesan` varchar(255) NOT NULL COMMENT 'Pesan motivasi/rekomendasi',
  `aktif` tinyint(1) DEFAULT 1,
  `urutan` int(11) DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `report_schedules`
--

DROP TABLE IF EXISTS `report_schedules`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `report_schedules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `report_type` enum('user_activity','tryout_results','content_performance','revenue') NOT NULL,
  `title` varchar(255) NOT NULL,
  `schedule_type` enum('daily','weekly','monthly') NOT NULL,
  `schedule_day` int(11) DEFAULT NULL COMMENT 'Day of week (1-7) or day of month (1-31)',
  `schedule_time` time DEFAULT NULL,
  `filters` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Report filters' CHECK (json_valid(`filters`)),
  `is_active` tinyint(1) DEFAULT 1,
  `last_run_at` timestamp NULL DEFAULT NULL,
  `next_run_at` timestamp NULL DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_report_type` (`report_type`),
  KEY `idx_is_active` (`is_active`),
  KEY `idx_next_run_at` (`next_run_at`),
  KEY `created_by` (`created_by`),
  CONSTRAINT `report_schedules_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Scheduled report generation';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `revision_queue`
--

DROP TABLE IF EXISTS `revision_queue`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `revision_queue` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `soal_id` int(11) NOT NULL,
  `priority` enum('low','medium','high','urgent') DEFAULT 'medium',
  `status` enum('pending','assigned','in_progress','completed','cancelled') DEFAULT 'pending',
  `assigned_to` int(11) DEFAULT NULL COMMENT 'User ID assigned to revision',
  `assigned_by` int(11) DEFAULT NULL COMMENT 'Admin who assigned',
  `assigned_at` timestamp NULL DEFAULT NULL,
  `reason` text DEFAULT NULL COMMENT 'Why this soal needs revision',
  `admin_notes` text DEFAULT NULL COMMENT 'Admin notes/comments',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `completed_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_soal_id` (`soal_id`),
  KEY `idx_status` (`status`),
  KEY `idx_priority` (`priority`),
  KEY `idx_assigned_to` (`assigned_to`),
  KEY `assigned_by` (`assigned_by`),
  CONSTRAINT `revision_queue_ibfk_1` FOREIGN KEY (`soal_id`) REFERENCES `questions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `revision_queue_ibfk_2` FOREIGN KEY (`assigned_to`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `revision_queue_ibfk_3` FOREIGN KEY (`assigned_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Revision queue for soal that need review';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `scheduled_tryout_registrations`
--

DROP TABLE IF EXISTS `scheduled_tryout_registrations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `scheduled_tryout_registrations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `scheduled_tryout_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `status` enum('registered','joined','completed','absent') DEFAULT 'registered',
  `registered_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_scheduled` (`scheduled_tryout_id`,`user_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `scheduled_tryout_registrations_ibfk_1` FOREIGN KEY (`scheduled_tryout_id`) REFERENCES `scheduled_tryouts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `scheduled_tryout_registrations_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `scheduled_tryouts`
--

DROP TABLE IF EXISTS `scheduled_tryouts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `scheduled_tryouts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) NOT NULL,
  `deskripsi` text DEFAULT NULL,
  `waktu_mulai` datetime NOT NULL,
  `durasi_menit` int(11) DEFAULT 90,
  `kuota` int(11) DEFAULT 100,
  `status` enum('draft','published','started','completed','cancelled') DEFAULT 'draft',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `session_subtes`
--

DROP TABLE IF EXISTS `session_subtes`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `session_subtes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session_id` int(11) NOT NULL,
  `subtes` enum('TKP','TIU','TWK') NOT NULL,
  `durasi_menit` int(11) NOT NULL DEFAULT 30,
  `jumlah_soal` int(11) NOT NULL DEFAULT 30,
  `passing_grade` int(11) NOT NULL DEFAULT 0,
  `nilai` int(11) NOT NULL DEFAULT 0 COMMENT 'Nilai akhir subtes setelah finish',
  `waktu_mulai_subtes` timestamp NULL DEFAULT NULL,
  `urutan` int(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_session_subtes` (`session_id`,`subtes`),
  KEY `idx_session_subtes_session` (`session_id`),
  CONSTRAINT `session_subtes_ibfk_1` FOREIGN KEY (`session_id`) REFERENCES `tryout_sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=764 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `soal_ai_cache`
--

DROP TABLE IF EXISTS `soal_ai_cache`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `soal_ai_cache` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `master_materi_id` int(11) NOT NULL,
  `pertanyaan` text NOT NULL,
  `pilihan_a` text NOT NULL,
  `pilihan_b` text NOT NULL,
  `pilihan_c` text NOT NULL,
  `pilihan_d` text NOT NULL,
  `pilihan_e` text NOT NULL,
  `jawaban_benar` char(1) NOT NULL,
  `bobot_tkp` int(11) DEFAULT NULL,
  `bobot_a` int(11) DEFAULT NULL,
  `bobot_b` int(11) DEFAULT NULL,
  `bobot_c` int(11) DEFAULT NULL,
  `bobot_d` int(11) DEFAULT NULL,
  `bobot_e` int(11) DEFAULT NULL,
  `pembahasan` text NOT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `passage_id` int(11) DEFAULT NULL,
  `tingkat_kesulitan` enum('mudah','sedang','sulit') DEFAULT 'sedang',
  `digenerate_pada` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `master_materi_id` (`master_materi_id`),
  KEY `passage_id` (`passage_id`),
  CONSTRAINT `soal_ai_cache_ibfk_1` FOREIGN KEY (`master_materi_id`) REFERENCES `master_materi` (`id`) ON DELETE CASCADE,
  CONSTRAINT `soal_ai_cache_ibfk_2` FOREIGN KEY (`passage_id`) REFERENCES `passages` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=229 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `soal_tag_relations`
--

DROP TABLE IF EXISTS `soal_tag_relations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `soal_tag_relations` (
  `soal_id` int(11) NOT NULL,
  `tag_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`soal_id`,`tag_id`),
  KEY `tag_id` (`tag_id`),
  CONSTRAINT `soal_tag_relations_ibfk_1` FOREIGN KEY (`soal_id`) REFERENCES `questions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `soal_tag_relations_ibfk_2` FOREIGN KEY (`tag_id`) REFERENCES `soal_tags` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Tag relations for questions';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `soal_tags`
--

DROP TABLE IF EXISTS `soal_tags`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `soal_tags` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tag_name` varchar(50) NOT NULL,
  `tag_color` varchar(20) DEFAULT '#2980b9',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `tag_name` (`tag_name`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Available tags for questions';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `soal_versions`
--

DROP TABLE IF EXISTS `soal_versions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `soal_versions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `soal_id` int(11) NOT NULL,
  `version` int(11) NOT NULL,
  `pertanyaan` text NOT NULL,
  `pilihan_a` text DEFAULT NULL,
  `pilihan_b` text DEFAULT NULL,
  `pilihan_c` text DEFAULT NULL,
  `pilihan_d` text DEFAULT NULL,
  `pilihan_e` text DEFAULT NULL,
  `jawaban_benar` char(1) NOT NULL,
  `pembahasan` text DEFAULT NULL,
  `tips` text DEFAULT NULL,
  `related_links` text DEFAULT NULL,
  `materi` text DEFAULT NULL,
  `image_url` text DEFAULT NULL,
  `bobot_tkp` int(11) DEFAULT NULL,
  `edited_by` int(11) DEFAULT NULL COMMENT 'User ID who made the edit',
  `edited_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_soal_id` (`soal_id`),
  KEY `idx_version` (`soal_id`,`version`),
  KEY `edited_by` (`edited_by`),
  CONSTRAINT `soal_versions_ibfk_1` FOREIGN KEY (`soal_id`) REFERENCES `questions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `soal_versions_ibfk_2` FOREIGN KEY (`edited_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Version history for questions';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `subtes_config`
--

DROP TABLE IF EXISTS `subtes_config`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `subtes_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `subtes` enum('TKP','TIU','TWK') NOT NULL,
  `durasi_menit` int(11) NOT NULL DEFAULT 30 COMMENT 'Durasi per subtes dalam menit',
  `jumlah_soal` int(11) NOT NULL DEFAULT 30 COMMENT 'Jumlah soal per subtes',
  `passing_grade` int(11) NOT NULL DEFAULT 0 COMMENT 'Nilai minimum lulus per subtes',
  `urutan` int(11) NOT NULL DEFAULT 1 COMMENT 'Urutan pengerjaan subtes',
  `aktif` tinyint(1) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_subtes` (`subtes`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `system_health`
--

DROP TABLE IF EXISTS `system_health`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `system_health` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `metric_name` varchar(100) NOT NULL,
  `metric_value` decimal(20,4) NOT NULL,
  `metric_unit` varchar(20) DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_metric_name` (`metric_name`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tips`
--

DROP TABLE IF EXISTS `tips`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tips` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `subtes` enum('TKP','TIU','TWK') NOT NULL,
  `tipe` varchar(20) DEFAULT NULL,
  `judul` varchar(200) NOT NULL,
  `konten` text NOT NULL,
  `urutan` int(11) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tips_tricks`
--

DROP TABLE IF EXISTS `tips_tricks`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tips_tricks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `subtes` enum('TKP','TIU','TWK') NOT NULL,
  `tipe` varchar(50) DEFAULT NULL,
  `topik` varchar(100) NOT NULL,
  `judul` varchar(200) NOT NULL,
  `tips` text NOT NULL COMMENT 'Singkat, padat, reusable',
  `contoh_soal` text NOT NULL,
  `contoh_penerapan` text NOT NULL,
  `contoh_jawaban` varchar(255) NOT NULL,
  `contoh_pembahasan` text NOT NULL,
  `urutan` int(11) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2131 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tryout_event_registrations`
--

DROP TABLE IF EXISTS `tryout_event_registrations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tryout_event_registrations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `event_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `registered_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_event` (`event_id`,`user_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `tryout_event_registrations_ibfk_1` FOREIGN KEY (`event_id`) REFERENCES `tryout_events` (`id`) ON DELETE CASCADE,
  CONSTRAINT `tryout_event_registrations_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='User registrations for tryout events';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tryout_events`
--

DROP TABLE IF EXISTS `tryout_events`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tryout_events` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) NOT NULL,
  `deskripsi` text DEFAULT NULL,
  `tanggal_mulai` datetime NOT NULL,
  `tanggal_selesai` datetime NOT NULL,
  `paket_soal_id` int(11) DEFAULT NULL,
  `passing_grade_custom` int(11) DEFAULT NULL COMMENT 'Custom passing grade for this event',
  `max_participants` int(11) DEFAULT NULL COMMENT 'Maximum participants (null = unlimited)',
  `aktif` tinyint(1) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `paket_soal_id` (`paket_soal_id`),
  CONSTRAINT `tryout_events_ibfk_1` FOREIGN KEY (`paket_soal_id`) REFERENCES `tryout_packages` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Tryout events for scheduled competitions';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tryout_packages`
--

DROP TABLE IF EXISTS `tryout_packages`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tryout_packages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nama` varchar(100) NOT NULL,
  `deskripsi` text DEFAULT NULL,
  `tingkat_kesulitan` enum('mudah','sedang','sulit') NOT NULL,
  `passing_grade_twk` int(11) DEFAULT 65,
  `passing_grade_tiu` int(11) DEFAULT 80,
  `passing_grade_tkp` int(11) DEFAULT 126,
  `durasi_twk` int(11) DEFAULT 30,
  `durasi_tiu` int(11) DEFAULT 35,
  `durasi_tkp` int(11) DEFAULT 45,
  `jumlah_soal_twk` int(11) DEFAULT 30,
  `jumlah_soal_tiu` int(11) DEFAULT 30,
  `jumlah_soal_tkp` int(11) DEFAULT 35,
  `aktif` tinyint(4) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tryout_sessions`
--

DROP TABLE IF EXISTS `tryout_sessions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tryout_sessions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `nama` varchar(100) NOT NULL,
  `durasi_tkp` int(11) DEFAULT 45,
  `durasi_tiu` int(11) DEFAULT 35,
  `durasi_twk` int(11) DEFAULT 30,
  `jumlah_tkp` int(11) DEFAULT 45,
  `jumlah_tiu` int(11) DEFAULT 35,
  `jumlah_twk` int(11) DEFAULT 30,
  `passing_tkp` int(11) DEFAULT 126,
  `passing_tiu` int(11) DEFAULT 80,
  `passing_twk` int(11) DEFAULT 65,
  `passing_total` int(11) DEFAULT 271,
  `waktu_mulai` datetime DEFAULT NULL,
  `waktu_selesai` datetime DEFAULT NULL,
  `nilai_tkp` int(11) DEFAULT 0,
  `nilai_tiu` int(11) DEFAULT 0,
  `nilai_twk` int(11) DEFAULT 0,
  `total_nilai` int(11) DEFAULT 0,
  `status` enum('berjalan','selesai','gagal') DEFAULT 'berjalan',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `strict_mode` tinyint(4) DEFAULT 0 COMMENT 'Strict mode: 1 = no back navigation, 0 = normal mode',
  `package_id` int(11) DEFAULT NULL COMMENT 'Reference to tryout_packages table',
  `pause_count` int(11) DEFAULT 0 COMMENT 'Number of times paused',
  `total_pause_seconds` int(11) DEFAULT 0 COMMENT 'Total paused time in seconds',
  `is_paused` tinyint(4) DEFAULT 0 COMMENT 'Currently paused: 1 = yes, 0 = no',
  `paused_at` timestamp NULL DEFAULT NULL COMMENT 'Timestamp when pause started',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `package_id` (`package_id`),
  KEY `idx_tryout_sessions_user` (`user_id`),
  KEY `idx_tryout_sessions_status` (`status`),
  CONSTRAINT `tryout_sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `tryout_sessions_ibfk_2` FOREIGN KEY (`package_id`) REFERENCES `tryout_packages` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=507 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `user_achievements`
--

DROP TABLE IF EXISTS `user_achievements`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `user_achievements` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `achievement_type` varchar(50) NOT NULL COMMENT 'Type: streak_7, streak_30, streak_100, perfect_score, etc',
  `achievement_name` varchar(100) NOT NULL,
  `achieved_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_achievement` (`user_id`,`achievement_type`),
  CONSTRAINT `user_achievements_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='User achievements and badges';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `user_activity_log`
--

DROP TABLE IF EXISTS `user_activity_log`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `user_activity_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `action` varchar(50) NOT NULL COMMENT 'Action performed (login, tryout_start, tryout_finish, etc.)',
  `details` text DEFAULT NULL COMMENT 'Additional details about the action',
  `ip_address` varchar(45) DEFAULT NULL COMMENT 'IP address of the user',
  `user_agent` varchar(255) DEFAULT NULL COMMENT 'Browser user agent',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_action` (`action`),
  KEY `idx_created_at` (`created_at`),
  CONSTRAINT `user_activity_log_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='User activity log for admin monitoring';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `user_audit_logs`
--

DROP TABLE IF EXISTS `user_audit_logs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `user_audit_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `action` varchar(100) NOT NULL,
  `details` text DEFAULT NULL,
  `ip_address` varchar(45) NOT NULL,
  `user_agent` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_action` (`action`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_user_audit_logs_user` (`user_id`),
  KEY `idx_user_audit_logs_action` (`action`),
  KEY `idx_user_audit_logs_created` (`created_at`),
  CONSTRAINT `user_audit_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5425 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `user_feedback`
--

DROP TABLE IF EXISTS `user_feedback`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `user_feedback` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `category` enum('saran','kritik','bug','fitur','lainnya') DEFAULT 'lainnya',
  `message` text NOT NULL,
  `status` enum('pending','dilihat','diproses','selesai','ditolak') DEFAULT 'pending',
  `admin_response` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `fk_feedback_user` (`user_id`),
  CONSTRAINT `user_feedback_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `user_quiz_difficulty`
--

DROP TABLE IF EXISTS `user_quiz_difficulty`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `user_quiz_difficulty` (
  `user_id` int(11) NOT NULL,
  `current_difficulty` enum('mudah','sedang','sulit') DEFAULT 'sedang',
  `consecutive_high_scores` int(11) DEFAULT 0 COMMENT 'Count of consecutive high scores (>=80%)',
  `consecutive_low_scores` int(11) DEFAULT 0 COMMENT 'Count of consecutive low scores (<50%)',
  `last_updated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`user_id`),
  CONSTRAINT `user_quiz_difficulty_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='User quiz difficulty progression tracking';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nama` varchar(100) NOT NULL,
  `email` varchar(100) DEFAULT NULL COMMENT 'Email (deprecated, gunakan no_hp)',
  `instansi_pilihan` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `role` enum('admin','user') DEFAULT 'user',
  `status` enum('active','suspended','banned') DEFAULT 'active' COMMENT 'User account status',
  `suspended_at` timestamp NULL DEFAULT NULL COMMENT 'Timestamp when user was suspended',
  `suspended_reason` text DEFAULT NULL COMMENT 'Reason for suspension',
  `instansi_id` int(11) DEFAULT NULL,
  `password_hash` varchar(255) DEFAULT NULL,
  `failed_attempts` int(11) DEFAULT 0,
  `lockout_until` datetime DEFAULT NULL,
  `instansi` varchar(100) DEFAULT NULL,
  `no_hp` varchar(20) DEFAULT NULL COMMENT 'Nomor HP untuk login (08xx)',
  `sekolah_asal` varchar(100) DEFAULT NULL COMMENT 'Nama sekolah asal (SMA/SMK/MA)',
  `tahun_tamat` int(11) DEFAULT NULL COMMENT 'Tahun tamat sekolah',
  `foto_profil` varchar(255) DEFAULT NULL COMMENT 'Path to profile photo',
  `tanggal_lahir` date DEFAULT NULL COMMENT 'Tanggal lahir user',
  `jenis_kelamin` enum('L','P') DEFAULT NULL COMMENT 'Jenis kelamin: L=Laki-laki, P=Perempuan',
  `alamat` text DEFAULT NULL COMMENT 'Alamat lengkap user',
  `show_leaderboard` tinyint(1) DEFAULT 1 COMMENT 'Show profile in leaderboard: 1=show, 0=hide',
  `notification_preference` enum('push','browser','both','none') DEFAULT 'browser' COMMENT 'Preferensi notifikasi',
  `language` varchar(5) DEFAULT 'id' COMMENT 'Bahasa: id=en, en=english',
  `theme` varchar(10) DEFAULT 'light' COMMENT 'Tema: light/dark',
  `font_size` varchar(10) DEFAULT 'medium' COMMENT 'Ukuran font: small/medium/large',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_no_hp` (`no_hp`),
  KEY `instansi_id` (`instansi_id`),
  KEY `idx_status` (`status`),
  CONSTRAINT `users_ibfk_1` FOREIGN KEY (`instansi_id`) REFERENCES `instansi` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=286 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Temporary view structure for view `v_tryout_sessions_flat`
--

DROP TABLE IF EXISTS `v_tryout_sessions_flat`;
/*!50001 DROP VIEW IF EXISTS `v_tryout_sessions_flat`*/;
SET @saved_cs_client     = @@character_set_client;
/*!50503 SET character_set_client = utf8mb4 */;
 1 AS `id`,
 1 AS `user_id`,
 1 AS `nama`,
 1 AS `waktu_mulai`,
 1 AS `waktu_selesai`,
 1 AS `status`,
 1 AS `created_at`,
 1 AS `durasi_twk_v`,
 1 AS `durasi_tiu_v`,
 1 AS `durasi_tkp_v`,
 1 AS `jumlah_twk_v`,
 1 AS `jumlah_tiu_v`,
 1 AS `jumlah_tkp_v`,
 1 AS `passing_twk_v`,
 1 AS `passing_tiu_v`,
 1 AS `passing_tkp_v`,
 1 AS `nilai_twk_v`,
 1 AS `nilai_tiu_v`,
 1 AS `nilai_tkp_v`*/;
SET character_set_client = @saved_cs_client;

--
-- Final view structure for view `v_tryout_sessions_flat`
--

/*!50001 DROP VIEW IF EXISTS `v_tryout_sessions_flat`*/;
/*!50001 SET @saved_cs_client          = @@character_set_client */;
/*!50001 SET @saved_cs_results         = @@character_set_results */;
/*!50001 SET @saved_col_connection     = @@collation_connection */;
/*!50001 SET character_set_client      = utf8 */;
/*!50001 SET character_set_results     = utf8 */;
/*!50001 SET collation_connection      = utf8_general_ci */;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50001 VIEW `v_tryout_sessions_flat` AS select `ts`.`id` AS `id`,`ts`.`user_id` AS `user_id`,`ts`.`nama` AS `nama`,`ts`.`waktu_mulai` AS `waktu_mulai`,`ts`.`waktu_selesai` AS `waktu_selesai`,`ts`.`status` AS `status`,`ts`.`created_at` AS `created_at`,max(case when `ss`.`subtes` = 'TWK' then `ss`.`durasi_menit` end) AS `durasi_twk_v`,max(case when `ss`.`subtes` = 'TIU' then `ss`.`durasi_menit` end) AS `durasi_tiu_v`,max(case when `ss`.`subtes` = 'TKP' then `ss`.`durasi_menit` end) AS `durasi_tkp_v`,max(case when `ss`.`subtes` = 'TWK' then `ss`.`jumlah_soal` end) AS `jumlah_twk_v`,max(case when `ss`.`subtes` = 'TIU' then `ss`.`jumlah_soal` end) AS `jumlah_tiu_v`,max(case when `ss`.`subtes` = 'TKP' then `ss`.`jumlah_soal` end) AS `jumlah_tkp_v`,max(case when `ss`.`subtes` = 'TWK' then `ss`.`passing_grade` end) AS `passing_twk_v`,max(case when `ss`.`subtes` = 'TIU' then `ss`.`passing_grade` end) AS `passing_tiu_v`,max(case when `ss`.`subtes` = 'TKP' then `ss`.`passing_grade` end) AS `passing_tkp_v`,max(case when `ss`.`subtes` = 'TWK' then `ss`.`nilai` end) AS `nilai_twk_v`,max(case when `ss`.`subtes` = 'TIU' then `ss`.`nilai` end) AS `nilai_tiu_v`,max(case when `ss`.`subtes` = 'TKP' then `ss`.`nilai` end) AS `nilai_tkp_v` from (`tryout_sessions` `ts` left join `session_subtes` `ss` on(`ts`.`id` = `ss`.`session_id`)) group by `ts`.`id` */;
/*!50001 SET character_set_client      = @saved_cs_client */;
/*!50001 SET character_set_results     = @saved_cs_results */;
/*!50001 SET collation_connection      = @saved_col_connection */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2026-06-13  0:26:42
